### PR TITLE
Including Gene Names/Aliases in output tables and HTML

### PR DESCRIPTION
**Pull request by warrenmcg**
Hi,

I was very excited to discover this tool after trying a few others that are attempting to apply similar approaches! I was glad to see the "gene.names" argument so that I didn't have to memorize Ensembl gene IDs, but I wanted to enhance the output files so that the output tables (both text files and the gene table on the front HTML page) could also have the gene names. 

Ideally, I would want the chance to include other gene metadata (e.g. full description, biotype) in the output, but including a variable number of columns could be tricky and implemented a few different ways (squashing it into featureData, having a separate "geneMetadata" slot, etc.). I think this is a good start.

Let me know what you think!
Warren

### CODE REVIEW

**Comment by hartleys** [comment]
Woah, excellent! Adding the gene names to these tables has been somewhere
in the middle of my to-do list for a while. But it looks like you've
basically done most of the work for me.

I'll shift this to the top of my list and hopefully have it folded into the
next release (probably early next week).

Adding more gene annotation to these tables is on my to-do list as well,
however doing it properly would require adding new features to QoRTs (which
is my other package), while also being careful to support backwards
compatibility with files generated by older versions of QoRTs. So it's a
little tricky, but it shouldn't be too bad.

**Comment by warrenmcg** [comment]
I'm glad to see that I was of some help! Looking forward to when this is brought into the next release!

**Comment by hartleys** [comment]
Folded this and related changes into the main branch by hand. Made a few modifications. For example: I didn't include gene name in the jscs object, since the jscs object is already overlarge and already contains a lot of extra data.

I somehow missed the second update to the HTML table wrapping. You're right that it looks better that way, and I'll fold it into the next release.

**Comment by warrenmcg** [comment]
Makes sense to me! I'll move to the new release. Great work!

**Pull request closed without merging**
